### ISSUE TITLE
Workspaces per project

### ISSUE THREAD

**Issue by adenot** [DNXLabs/one-cli#1]
List of workspaces should be stored and read from the current folder (project).

That way the list of workspace can be part of the project code.

Story:
A developer,
*  clones the project repository
* types `one terraform init`
* selects workspace
* types `one terraform plan`
* works
Should work out of the box without previous knowledge of AWS accounts or roles.

**Comment by arthurbdiniz** [comment]
Since [v0.1.0](https://github.com/DNXLabs/one-cli/releases/tag/0.1.0) we already implement this feature of workspaces this way.
