### ISSUE TITLE
Script to perform CLI installation

### ISSUE THREAD

**Issue by arthurbdiniz** [DNXLabs/one-cli#10]
As a developer, I would like to have one single script .sh to install and configure the CLI.

**Comment by helderklemp** [comment]
might be worth to invest in brew for mac os?

**Comment by arthurbdiniz** [comment]
> might be worth to invest in brew for mac os?

I think will worth more in the future when the tool become more mature.

For now, I will create another issue aiming this context of brew and put it as an ice block to keep track.
