### ISSUE TITLE
Release 0.6.8 is missing MacOS and Linux packages for download

### ISSUE THREAD

**Issue by sohflp** [DNXLabs/one-cli#104]
### Issue Summary

After trying to update the One CLI to the latest version (0.6.8) I couldn't execute `one --version` after installation. The following message appeared:

```
/usr/local/bin/one: line 1: Not: command not found
```

I decided to troubleshoot the installation script `get_one.sh` and I noticed there are expected two files, one for Linux and another for MacOS.

- one_linux_amd64
- one_macos_amd64

After reviewing the releases page I noticed the files were missing for version 0.6.8.

https://github.com/DNXLabs/one-cli/releases

## Steps to Reproduce the Problem

  1. Open README file and follow the installation instructions
  2. Hit the command `curl -sSL https://raw.githubusercontent.com/DNXLabs/one-cli/master/get_one.sh | bash`
  3. Hit the command `one --version`
  4. The following message appears in the screen `/usr/local/bin/one: line 1: Not: command not found`

I followed the steps to install the version 0.6.7 and it started to work fine.

## Specifications

  - Version: 0.6.8
  - Platform: macOS
  - Installation method: Binary

**Comment by arthurbdiniz** [comment]
Looking at the runner's logs something when wrong when the action tried to upload the artifact to gh actions S3 bucket. So I re-run all jobs and now the release has all binaries.

https://github.com/DNXLabs/one-cli/releases/tag/0.6.8
